//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.23 at 01:00:34 AM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nitec.kz/unidic/ws/getdata",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://nitec.kz/unidic/ws/getdata", prefix = "")})
package kz.nitec.unidic.request;