//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.20 at 11:25:47 PM ALMT 
//


package kz.nitec.unidic.items;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Item" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="Parent" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="ChildsCount" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                   &lt;element name="IsMarkedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="name_ru" type="{http://nitec.kz/unidic/items}Tname_ru"/&gt;
 *                   &lt;element name="name_kz" type="{http://nitec.kz/unidic/items}Tname_kz"/&gt;
 *                   &lt;element name="abbr_ru" type="{http://nitec.kz/unidic/items}Tabbr_ru"/&gt;
 *                   &lt;element name="abbr_kz" type="{http://nitec.kz/unidic/items}Tabbr_kz"/&gt;
 *                   &lt;element name="member" type="{http://nitec.kz/unidic/items}Tmember"/&gt;
 *                   &lt;element name="code" type="{http://nitec.kz/unidic/items}Tcode"/&gt;
 *                   &lt;element name="isEsedo" type="{http://nitec.kz/unidic/items}TisEsedo"/&gt;
 *                   &lt;element name="isReady" type="{http://nitec.kz/unidic/items}TisReady"/&gt;
 *                   &lt;element name="ElementGUID" type="{http://nitec.kz/unidic/items}TElementGUID"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item"
})
@XmlRootElement(name = "Items")
public class Items {

    @XmlElement(name = "Item")
    protected List<Items.Item> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Items.Item }
     * 
     * 
     */
    public List<Items.Item> getItem() {
        if (item == null) {
            item = new ArrayList<Items.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="Parent" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="ChildsCount" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *         &lt;element name="IsMarkedToDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="name_ru" type="{http://nitec.kz/unidic/items}Tname_ru"/&gt;
     *         &lt;element name="name_kz" type="{http://nitec.kz/unidic/items}Tname_kz"/&gt;
     *         &lt;element name="abbr_ru" type="{http://nitec.kz/unidic/items}Tabbr_ru"/&gt;
     *         &lt;element name="abbr_kz" type="{http://nitec.kz/unidic/items}Tabbr_kz"/&gt;
     *         &lt;element name="member" type="{http://nitec.kz/unidic/items}Tmember"/&gt;
     *         &lt;element name="code" type="{http://nitec.kz/unidic/items}Tcode"/&gt;
     *         &lt;element name="isEsedo" type="{http://nitec.kz/unidic/items}TisEsedo"/&gt;
     *         &lt;element name="isReady" type="{http://nitec.kz/unidic/items}TisReady"/&gt;
     *         &lt;element name="ElementGUID" type="{http://nitec.kz/unidic/items}TElementGUID"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "parent",
        "childsCount",
        "isMarkedToDelete",
        "nameRu",
        "nameKz",
        "abbrRu",
        "abbrKz",
        "member",
        "code",
        "isEsedo",
        "isReady",
        "elementGUID"
    })
    public static class Item {

        @XmlElement(name = "Id", required = true)
        protected BigInteger id;
        @XmlElement(name = "Parent", required = true)
        protected BigInteger parent;
        @XmlElement(name = "ChildsCount", required = true)
        protected BigInteger childsCount;
        @XmlElement(name = "IsMarkedToDelete")
        protected boolean isMarkedToDelete;
        @XmlElement(name = "name_ru", required = true)
        protected String nameRu;
        @XmlElement(name = "name_kz", required = true)
        protected String nameKz;
        @XmlElement(name = "abbr_ru", required = true)
        protected String abbrRu;
        @XmlElement(name = "abbr_kz", required = true)
        protected String abbrKz;
        @XmlElement(required = true, nillable = true)
        protected BigDecimal member;
        @XmlElement(required = true)
        protected String code;
        @XmlElement(required = true)
        protected String isEsedo;
        @XmlElement(required = true)
        protected String isReady;
        @XmlElement(name = "ElementGuid", required = true)
        protected BigDecimal elementGUID;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(BigInteger value) {
            this.id = value;
        }

        /**
         * Gets the value of the parent property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getParent() {
            return parent;
        }

        /**
         * Sets the value of the parent property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setParent(BigInteger value) {
            this.parent = value;
        }

        /**
         * Gets the value of the childsCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getChildsCount() {
            return childsCount;
        }

        /**
         * Sets the value of the childsCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setChildsCount(BigInteger value) {
            this.childsCount = value;
        }

        /**
         * Gets the value of the isMarkedToDelete property.
         * 
         */
        public boolean isIsMarkedToDelete() {
            return isMarkedToDelete;
        }

        /**
         * Sets the value of the isMarkedToDelete property.
         * 
         */
        public void setIsMarkedToDelete(boolean value) {
            this.isMarkedToDelete = value;
        }

        /**
         * Gets the value of the nameRu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameRu() {
            return nameRu;
        }

        /**
         * Sets the value of the nameRu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameRu(String value) {
            this.nameRu = value;
        }

        /**
         * Gets the value of the nameKz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameKz() {
            return nameKz;
        }

        /**
         * Sets the value of the nameKz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameKz(String value) {
            this.nameKz = value;
        }

        /**
         * Gets the value of the abbrRu property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAbbrRu() {
            return abbrRu;
        }

        /**
         * Sets the value of the abbrRu property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAbbrRu(String value) {
            this.abbrRu = value;
        }

        /**
         * Gets the value of the abbrKz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAbbrKz() {
            return abbrKz;
        }

        /**
         * Sets the value of the abbrKz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAbbrKz(String value) {
            this.abbrKz = value;
        }

        /**
         * Gets the value of the member property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMember() {
            return member;
        }

        /**
         * Sets the value of the member property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMember(BigDecimal value) {
            this.member = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the isEsedo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsEsedo() {
            return isEsedo;
        }

        /**
         * Sets the value of the isEsedo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsEsedo(String value) {
            this.isEsedo = value;
        }

        /**
         * Gets the value of the isReady property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsReady() {
            return isReady;
        }

        /**
         * Sets the value of the isReady property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsReady(String value) {
            this.isReady = value;
        }

        /**
         * Gets the value of the elementGUID property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getElementGUID() {
            return elementGUID;
        }

        /**
         * Sets the value of the elementGUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setElementGUID(BigDecimal value) {
            this.elementGUID = value;
        }

    }

}
